server:
  port: 8088
spring:
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/tempvs_user}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:pass}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:client_id}
            client-secret: ${GOOGLE_CLIENT_SECRET:client_secret}
            redirect-uri: ${GOOGLE_REDIRECT_URI:{baseUrl}/api/user/login/oauth2/code/{registrationId}}
app:
  base-url: http://localhost:8080
  ui-url: ${APP_UI_URL:http://localhost:3000}
authorization:
  token: ${SECURITY_TOKEN:security_token}
email:
  service:
    url: ${EMAIL_SERVICE_URL:localhost:8081}
