databaseChangeLog:
- changeSet:
    id: 1772147116887-1
    author: anton (generated)
    changes:
    - createTable:
        columns:
        - column:
            autoIncrement: true
            constraints:
              nullable: false
              primaryKey: true
              primaryKeyName: app_userPK
            name: id
            type: BIGINT
        - column:
            name: account_non_expired
            type: BOOLEAN
        - column:
            name: account_non_locked
            type: BOOLEAN
        - column:
            name: credentials_non_expired
            type: BOOLEAN
        - column:
            name: current_profile_id
            type: BIGINT
        - column:
            name: email
            type: VARCHAR(255)
        - column:
            name: enabled
            type: BOOLEAN
        - column:
            name: password
            type: VARCHAR(255)
        - column:
            name: time_zone
            type: VARCHAR(255)
        tableName: app_user
- changeSet:
    id: 1772147116887-2
    author: anton (generated)
    changes:
    - createTable:
        columns:
        - column:
            constraints:
              nullable: false
            name: app_user_id
            type: BIGINT
        - column:
            name: roles
            type: VARCHAR(255)
        tableName: app_user_roles
- changeSet:
    id: 1772147116887-3
    author: anton (generated)
    changes:
    - createTable:
        columns:
        - column:
            autoIncrement: true
            constraints:
              nullable: false
              primaryKey: true
              primaryKeyName: email_verificationPK
            name: id
            type: BIGINT
        - column:
            name: created_date
            type: TIMESTAMP(6) WITH TIME ZONE
        - column:
            name: email
            type: VARCHAR(255)
        - column:
            name: verification_id
            type: VARCHAR(255)
        tableName: email_verification
- changeSet:
    id: 1772147116887-4
    author: anton (generated)
    changes:
    - addUniqueConstraint:
        columnNames: email
        constraintName: UC_APP_USEREMAIL_COL
        tableName: app_user
- changeSet:
    id: 1772147116887-5
    author: anton (generated)
    changes:
    - addForeignKeyConstraint:
        baseColumnNames: app_user_id
        baseTableName: app_user_roles
        constraintName: FKkwxexnudtp5gmt82j0qtytnoe
        deferrable: false
        initiallyDeferred: false
        referencedColumnNames: id
        referencedTableName: app_user
        validate: true

